# This is a basic workflow to help you get started with Actions

name: generateDocs

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - '**.md'
    - '**.yml'  
    

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: docs_csharp
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - run: |
          echo generate help file
          mkdir output
          git pull

    - name: generate html
      uses: docker://pandoc/latex:2.9
      with: # needs a README in your repo root!
          #args: "--standalone --output=output/README.html README.md"
        args: "README.md docs/Demo.md docs/FAQ.md docs/Author.md --standalone -f gfm -t html  --toc -o output/output.html --metadata title=WebAPI2CLI"

    - name: generate pdf
      uses: docker://pandoc/latex:2.9
      with: # needs a README in your repo root!
          #args: "--standalone --output=output/README.html README.md"
        args: "README.md docs/Demo.md docs/FAQ.md docs/Author.md --standalone -f gfm -t pdf  --toc -o output/output.pdf --metadata title=WebAPI2CLI"

    - run: |
        cp ./output/output.html ./docs/index.html
        cp ./output/output.pdf ./docs/Web2CLI.pdf
        rm -rf ./output
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "generate html" -a --allow-empty
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


  docs_csharp:
    # The type of runner that the job will run on
    runs-on: windows-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: run list packages
      run: |                
        cd src
        dotnet list WebAPI2CLI.sln package > docs/packageList.md
        dotnet list WebAPI2CLI.sln package --outdated > docs/packageOutdated.md
      shell: cmd

    - name: run documentation
      run: |                
        DocumentationSources.bat
      shell: cmd

    - name: run commit`
      run: |                      
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "generate documentation sources" -a --allow-empty
      shell: cmd
           
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

